"""
Runtime helpers for the parallel keypoint pipeline.

This module is imported by every Isaac Sim script generated by the pipeline.
It provides JSON helpers, quaternion math, EE helpers, IK wrappers, keypoint
functions, contact forces, and the auto-render world.step wrapper.

Usage from the thin boilerplate template:
    from boilerplate_runtime import (
        _NumpyEncoder, json_safe,
        _qnorm, _qconj, _qmul, _qmat, _qrotate,
        _get_link_world_pos,
        get_ee_pos_env0, get_ee_pos_all_envs,
        compute_keypoints, compute_keypoints_batch,
        setup_ik, init_render, init_runtime,
        solve_ik_env0, solve_ik_for_env, solve_ik_batch_all_envs,
        get_object_contact_forces, keypoint_max_dist_batch,
    )
    # 1. Call init_render() BEFORE the physics settle loop.
    # 2. Call init_runtime() AFTER computing GOAL_KEYPOINTS_BATCH.
"""
from __future__ import annotations
import os, json
import numpy as np


# ─── JSON helpers ──────────────────────────────────────────────────────────────

class _NumpyEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, np.integer):  return int(o)
        if isinstance(o, np.floating): return float(o)
        if isinstance(o, np.ndarray):  return o.tolist()
        return super().default(o)


def json_safe(obj):
    """Recursively strip numpy scalars/arrays so the result is json.dumps-safe.
    Use for any json.dumps call that may touch numpy values, e.g.:
        json.dumps(json_safe({"pos": arr[0], "val": arr[i,j]}))
    Individual numpy scalar indexing (arr[i,j]) is NOT auto-converted — always
    wrap with float(arr[i,j]) or use this helper on the whole dict."""
    if isinstance(obj, dict):
        return {k: json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [json_safe(v) for v in obj]
    if isinstance(obj, np.integer):  return int(obj)
    if isinstance(obj, np.floating): return float(obj)
    if isinstance(obj, np.ndarray):  return obj.tolist()
    return obj


# ─── Quaternion helpers (wxyz convention) ──────────────────────────────────────

def _qnorm(q):
    q = np.asarray(q, dtype=np.float64)
    return q / (np.linalg.norm(q) + 1e-12)


def _qconj(q):
    q = np.asarray(q, dtype=np.float64)
    return np.array([q[0], -q[1], -q[2], -q[3]])


def _qmul(q1, q2):
    w1, x1, y1, z1 = q1; w2, x2, y2, z2 = q2
    return np.array([
        w1*w2 - x1*x2 - y1*y2 - z1*z2,
        w1*x2 + x1*w2 + y1*z2 - z1*y2,
        w1*y2 - x1*z2 + y1*w2 + z1*x2,
        w1*z2 + x1*y2 - y1*x2 + z1*w2,
    ], dtype=np.float64)


def _qmat(q):
    w, x, y, z = _qnorm(q)
    return np.array([
        [1-2*(y*y+z*z), 2*(x*y-w*z),   2*(x*z+w*y)  ],
        [2*(x*y+w*z),   1-2*(x*x+z*z), 2*(y*z-w*x)  ],
        [2*(x*z-w*y),   2*(y*z+w*x),   1-2*(x*x+y*y)],
    ], dtype=np.float64)


def _qrotate(q, v):
    q = _qnorm(q)
    qv = np.array([0.0, v[0], v[1], v[2]])
    r = _qmul(_qmul(q, qv), _qconj(q))
    return r[1:]


# ─── EE frame offset constant ─────────────────────────────────────────────────
# xhand_mount_right (IK EE frame) is this far BEHIND the knuckle centroid along
# the approach direction. Add this to standoff targets when solving IK so the
# knuckle lands at the intended distance from the object:
#   ik_target = obj_pos + approach_dir * (desired_knuckle_standoff + IK_EE_MOUNT_ADJ_M)
IK_EE_MOUNT_ADJ_M: float = 0.10

# ─── USD / stage link-position helper ─────────────────────────────────────────

def _get_link_world_pos(stage, path):
    """Return (3,) world position of a USD prim, or None."""
    try:
        from pxr import UsdGeom
        _p = stage.GetPrimAtPath(path)
        if _p.IsValid():
            _xf = UsdGeom.Xformable(_p).ComputeLocalToWorldTransform(0)
            _t  = _xf.ExtractTranslation()
            pos = np.array([float(_t[0]), float(_t[1]), float(_t[2])])
            if np.any(pos != 0):
                return pos
    except Exception:
        pass
    return None


def _get_link_world_transform(stage, path):
    """Return (pos(3,), quat_wxyz(4,)) world transform of a USD prim, or (None, None)."""
    try:
        from pxr import UsdGeom, Gf
        _p = stage.GetPrimAtPath(path)
        if _p.IsValid():
            _xf_mat = UsdGeom.Xformable(_p).ComputeLocalToWorldTransform(0)
            _t = _xf_mat.ExtractTranslation()
            pos = np.array([float(_t[0]), float(_t[1]), float(_t[2])])
            _rot_mat = _xf_mat.ExtractRotationMatrix()
            _rot = Gf.Rotation(_rot_mat)
            _q   = _rot.GetQuaternion()
            _im  = _q.GetImaginary()
            quat_wxyz = np.array([float(_q.GetReal()),
                                   float(_im[0]), float(_im[1]), float(_im[2])],
                                  dtype=np.float64)
            # Normalise
            n = np.linalg.norm(quat_wxyz)
            if n > 1e-8:
                quat_wxyz /= n
            if np.any(pos != 0) or np.any(quat_wxyz[1:] != 0):
                return pos, quat_wxyz
    except Exception:
        pass
    return None, None


# ─── EE (end-effector) grasp-centroid helpers ──────────────────────────────────

# Outermost knuckle links (MCP level) — one per finger.
_KNUCKLE_LINKS = [
    "right_hand_index_bend_link",
    "right_hand_mid_bend_link",
    "right_hand_ring_bend_link",
    "right_hand_pinky_bend_link",
    "right_hand_thumb_bend_link",
]
_WRIST_LINKS    = ["right_hand_ee_link", "right_hand_link"]
_FALLBACK_LINKS = ["right_hand_ee_link", "right_hand_thumb_bend_link",
                   "right_hand_link", "right_hand_palm_link"]


def _ee_grasp_centroid(stage, env_i):
    """Centroid of knuckle links biased 30% toward wrist = palm grasp centre."""
    prefix = f"/World/envs/env_{env_i}/Robot/"
    knuckle_positions = [
        p for p in (_get_link_world_pos(stage, prefix + ln) for ln in _KNUCKLE_LINKS)
        if p is not None
    ]
    if len(knuckle_positions) >= 2:
        centroid = np.mean(knuckle_positions, axis=0)
        for wl in _WRIST_LINKS:
            wrist = _get_link_world_pos(stage, prefix + wl)
            if wrist is not None:
                # 70% knuckle centroid + 30% wrist = between knuckles and wrist
                return 0.7 * centroid + 0.3 * wrist
        return centroid
    for ln in _FALLBACK_LINKS:
        pos = _get_link_world_pos(stage, prefix + ln)
        if pos is not None:
            return pos
    return None


def get_ee_pos_env0(stage):
    pos = _ee_grasp_centroid(stage, 0)
    if pos is not None:
        print("EE_LINK_USED: knuckle_centroid env_0", flush=True)
    return pos


def get_ee_pos_all_envs(stage, n_envs):
    """Return list of (3,) arrays (one per env), or None where lookup fails."""
    return [_ee_grasp_centroid(stage, ei) for ei in range(n_envs)]


def get_ee_transforms_all_envs(stage, n_envs):
    """Return (pos_list, quat_list) — both length n_envs.
    pos_list[i]:  (3,) EE world position (grasp centroid), or None on failure.
    quat_list[i]: (4,) EE wrist orientation (wxyz) from right_hand_ee_link, or None.
    Use quat_list as target_quats in solve_ik_batch_all_envs to constrain wrist orientation."""
    pos_list  = []
    quat_list = []
    for ei in range(n_envs):
        pos = _ee_grasp_centroid(stage, ei)
        pos_list.append(pos)
        prefix = f"/World/envs/env_{ei}/Robot/"
        quat = None
        for ln in _WRIST_LINKS:
            _, q = _get_link_world_transform(stage, prefix + ln)
            if q is not None:
                quat = q
                break
        quat_list.append(quat)
    return pos_list, quat_list


# ─── Keypoint helpers ──────────────────────────────────────────────────────────

_KEYPOINT_OFFSETS = np.array([
    [ 1,  1,  1], [ 1,  1, -1], [-1, -1,  1], [-1, -1, -1]
], dtype=np.float64)


def compute_keypoints(pos, quat_wxyz, extents=None):
    """Single-env keypoint computation. Returns (4,3).
    extents defaults to OBJECT_EXTENTS set by init_runtime()."""
    e = _OBJECT_EXTENTS if extents is None else np.asarray(extents, dtype=np.float64)
    R = _qmat(quat_wxyz)
    local = _KEYPOINT_OFFSETS * (e / 2.0)
    return (R @ local.T).T + np.asarray(pos, dtype=np.float64)


def compute_keypoints_batch(positions, quats, extents=None):
    """Batch keypoint computation. positions: (N,3), quats: (N,4) [wxyz]. Returns (N,4,3)."""
    e = _OBJECT_EXTENTS if extents is None else np.asarray(extents, dtype=np.float64)
    local = _KEYPOINT_OFFSETS * (e / 2.0)   # (4,3)
    N = positions.shape[0]
    kps = np.zeros((N, 4, 3), dtype=np.float64)
    for _bi in range(N):
        R = _qmat(quats[_bi])
        kps[_bi] = (R @ local.T).T + positions[_bi]
    return kps


# ─── IK backend setup ──────────────────────────────────────────────────────────

_IK_URDF_PATH = (
    "/juno/u/jiaqis7/Dynamic-Dexterous-Digital-Cousin-Benchmark"
    "/scripts/keypoint_pipeline_par/assets/kinova_xhand/urdf"
    "/GEN3_URDF_V12_with_hand_right.urdf"
)
_IK_SCRIPT_DIR = (
    "/juno/u/jiaqis7/Dynamic-Dexterous-Digital-Cousin-Benchmark"
    "/scripts/keypoint_pipeline_par"
)


def setup_ik(dof_idx: dict) -> tuple:
    """Initialize IK backends: cuRobo (GPU) + numpy fallback always loaded.

    When cuRobo is available it is used as the primary solver. Numpy IK is
    always loaded alongside cuRobo so that envs whose cuRobo solve fails can
    fall back to incremental Jacobian steps (numpy always makes progress even
    when not fully converged, breaking the stuck-at-seed loop).

    Must be called AFTER SimulationApp starts.
    Returns (ik_backend: str, ik_open, ik_closed).
    Pass the result to init_runtime()."""
    import sys as _sys, os as _os
    import boilerplate_runtime as _brt
    # Store dof_idx early so run_ik_diagnostics (called before init_runtime) can use it
    _brt._dof_idx = dof_idx
    _os.environ["TORCH_CUDA_ARCH_LIST"] = "8.9;12.0"
    # Insert our src/ dir first so our updated solve_ik_curobo.py takes priority
    # over the copy in _IK_SCRIPT_DIR (which uses the old cuRobo v1 API).
    _SRC_DIR = _os.path.dirname(_os.path.abspath(__file__))
    if _SRC_DIR not in _sys.path:
        _sys.path.insert(0, _SRC_DIR)
    if _IK_SCRIPT_DIR not in _sys.path:
        _sys.path.append(_IK_SCRIPT_DIR)

    # Always try to load numpy IK so it can serve as fallback for cuRobo failures.
    try:
        from solve_ik_numpy import NumpyArmIK as _NumpyArmIK
        _brt._IK_NUMPY = _NumpyArmIK(
            urdf_path=_IK_URDF_PATH,
            ee_link_name="xhand_mount_right",
            arm_joint_names=[f"Actuator{i}" for i in range(1, 8)],
            damping=1e-6, max_iters=100, eps=1e-3, dq_max=0.15,
        )
        print("IK_NUMPY_FALLBACK: loaded (will step failed cuRobo envs forward)", flush=True)
    except Exception as _numpy_load_err:
        print(f"IK_NUMPY_FALLBACK: unavailable ({_numpy_load_err})", flush=True)
        _brt._IK_NUMPY = None

    try:
        from solve_ik_curobo import (CuRoboArmIK as _CuRoboArmIK, HAND_CLOSED as _HAND_CLOSED_DICT,
                                      _URDF_WORLD_TO_BASE_XYZ as _WB_XYZ,
                                      _URDF_WORLD_TO_BASE_RPY_Y as _WB_RPY_Y)
        import numpy as _np_ik
        ik_open = _CuRoboArmIK(
            urdf_path=_IK_URDF_PATH,
            ee_link_name="xhand_mount_right",
            arm_joint_names=[f"Actuator{i}" for i in range(1, 8)],
            num_seeds=200,
            position_threshold=0.005,
            world_to_base_xyz=_np_ik.array(_WB_XYZ),
            world_to_base_rpy_y=float(_WB_RPY_Y),
        )
        ik_closed = ik_open.with_hand_pose(_HAND_CLOSED_DICT)
        ik_backend = "curobo"
        print(
            f"IK_READY: curobo n_arm_dof={ik_open.n_arm_dofs} "
            f"joints={ik_open.arm_joint_names}",
            flush=True,
        )
    except Exception as _curobo_err:
        print(f"IK_CUROBO_UNAVAILABLE: {_curobo_err}", flush=True)
        if _brt._IK_NUMPY is not None:
            ik_open    = _brt._IK_NUMPY
            ik_closed  = _brt._IK_NUMPY
            ik_backend = "numpy"
            print(
                f"IK_READY: numpy_ik n_arm_dof={ik_open.n_arm_dofs} "
                f"joints={ik_open.arm_joint_names}",
                flush=True,
            )
        else:
            print("IK_UNAVAILABLE: no solver available — IK calls will return seed unchanged", flush=True)
            ik_open = ik_closed = None
            ik_backend = "none"

    print(f"IK_BACKEND: {ik_backend}", flush=True)
    return ik_backend, ik_open, ik_closed


# ─── MotionGen state and helpers ──────────────────────────────────────────────

# Arm joint names for the 7-DOF Kinova (Actuator1–7), in cspace order.
_MG_ARM_JOINT_NAMES = [
    "Actuator1", "Actuator2", "Actuator3", "Actuator4",
    "Actuator5", "Actuator6", "Actuator7",
]

# Inline robot config for MotionGen — matches debug_ik.py (validated).
# base_link → xhand_mount_right (7 DOF arm only; hand joints excluded automatically).
_MG_ROBOT_CFG = {
    "kinematics": {
        "base_link":       "base_link",
        "ee_link":         "xhand_mount_right",
        "urdf_path":       _IK_URDF_PATH,
        "asset_root_path": os.path.dirname(_IK_URDF_PATH),
        "collision_link_names": [
            "base_link", "Shoulder_Link", "HalfArm1_Link", "HalfArm2_Link",
            "ForeArm_Link", "SphericalWrist1_Link", "SphericalWrist2_Link",
            "Bracelet_Link", "xhand_mount_right",
        ],
        "collision_spheres": {
            "base_link":            [{"center": [0.0, 0.0,    0.06],  "radius": 0.06}],
            "Shoulder_Link":        [{"center": [0.0, 0.0,   -0.1],   "radius": 0.06},
                                     {"center": [0.0, 0.0,   -0.15],  "radius": 0.05}],
            "HalfArm1_Link":        [{"center": [0.0,  0.0,   0.0],   "radius": 0.055},
                                     {"center": [0.0, -0.07,  0.0],   "radius": 0.055},
                                     {"center": [0.0, -0.15,  0.0],   "radius": 0.055}],
            "HalfArm2_Link":        [{"center": [0.0,  0.0,   0.0],   "radius": 0.055},
                                     {"center": [0.0,  0.0,  -0.07],  "radius": 0.055},
                                     {"center": [0.0,  0.0,  -0.15],  "radius": 0.055}],
            "ForeArm_Link":         [{"center": [0.0,  0.0,   0.0],   "radius": 0.055},
                                     {"center": [0.0, -0.07,  0.0],   "radius": 0.055},
                                     {"center": [0.0, -0.17,  0.0],   "radius": 0.055}],
            "SphericalWrist1_Link": [{"center": [0.0,  0.0,   0.0],   "radius": 0.055},
                                     {"center": [0.0,  0.0,  -0.085], "radius": 0.055}],
            "SphericalWrist2_Link": [{"center": [0.0,  0.0,    0.0],  "radius": 0.05},
                                     {"center": [0.0, -0.085,  0.0],  "radius": 0.05}],
            "Bracelet_Link":        [{"center": [0.0,  0.0,  -0.05],  "radius": 0.04},
                                     {"center": [0.0, -0.05, -0.05],  "radius": 0.04}],
            "xhand_mount_right":    [{"center": [0.0,  0.0,   0.04],  "radius": 0.04}],
        },
        "collision_sphere_buffer": 0.005,
        "self_collision_ignore": {
            "base_link":            ["Shoulder_Link"],
            "Shoulder_Link":        ["HalfArm1_Link"],
            "HalfArm1_Link":        ["HalfArm2_Link"],
            "HalfArm2_Link":        ["ForeArm_Link"],
            "ForeArm_Link":         ["SphericalWrist1_Link"],
            "SphericalWrist1_Link": ["SphericalWrist2_Link"],
            "SphericalWrist2_Link": ["Bracelet_Link"],
            "Bracelet_Link":        ["xhand_mount_right"],
        },
        "self_collision_buffer": {k: 0.0 for k in [
            "base_link", "Shoulder_Link", "HalfArm1_Link", "HalfArm2_Link",
            "ForeArm_Link", "SphericalWrist1_Link", "SphericalWrist2_Link",
            "Bracelet_Link", "xhand_mount_right",
        ]},
        "cspace": {
            "joint_names":            _MG_ARM_JOINT_NAMES,
            # Initial arm config from the task layout — used for null-space regularisation.
            "retract_config":         [-1.529021,  1.545096,  0.164424,
                                        0.946070,  1.254565, -1.063086,  0.235436],
            "null_space_weight":      [1.0] * 7,
            "cspace_distance_weight": [1.0] * 7,
            "max_acceleration":       25.0,
            "max_jerk":               500.0,
        },
    }
}


def setup_motion_gen():
    """Initialize cuRobo MotionGen for the 7-DOF Kinova arm.

    Robot model: base_link → xhand_mount_right (Actuator1-7 only).
    World collision disabled (world_model=None) — arm self-collision only.
    use_cuda_graph=False prevents CUDA graph conflicts with Isaac Sim.

    Returns the MotionGen instance, also stored as module-level _MOTION_GEN.
    Call once after SimulationApp starts, alongside setup_ik().
    Returns None and prints a warning if cuRobo is unavailable."""
    import boilerplate_runtime as _brt
    try:
        from curobo.wrap.reacher.motion_gen import (
            MotionGen as _MG,
            MotionGenConfig as _MGCfg,
        )
        from curobo.types.base import TensorDeviceType as _TDA

        _ta = _TDA()
        _mg_cfg = _MGCfg.load_from_robot_config(
            _MG_ROBOT_CFG,
            world_model=None,       # no world obstacles; skips primitive_collision_cfg
            tensor_args=_ta,
            num_ik_seeds=32,
            num_trajopt_seeds=4,
            interpolation_dt=0.02,  # 50 Hz interpolated trajectory
            self_collision_check=True,
            self_collision_opt=True,
            use_cuda_graph=False,   # avoids CUDA graph conflicts with Isaac Sim
        )
        _mg = _MG(_mg_cfg)
        _brt._MOTION_GEN = _mg
        _brt._MOTION_GEN_TENSOR_ARGS = _ta
        print("MOTION_GEN_READY: MotionGen initialized (7-DOF Kinova arm, 50 Hz)", flush=True)
        return _mg
    except Exception as _e:
        import traceback as _tb
        print(f"MOTION_GEN_UNAVAILABLE: {_e}", flush=True)
        _brt._MOTION_GEN = None
        _brt._MOTION_GEN_TENSOR_ARGS = None
        return None


def plan_motion_all_envs(goal_cmds_full, start_cmds_full, n_wp_fallback=100):
    """Plan collision-free arm trajectories for ALL envs using MotionGen.

    For each env, runs GPU trajectory optimisation from start to the goal pose
    implied by FK(goal_arm_joints).  Environments whose plans fail fall back to
    linear interpolation in joint space.

    Args:
        goal_cmds_full:  (N_ENVS, n_dof)  full joint target from solve_ik_batch_all_envs.
        start_cmds_full: (N_ENVS, n_dof)  current full joint positions.
        n_wp_fallback:   waypoints for linear fallback (default 100 ≈ 2 s at 50 Hz).

    Returns:
        np.ndarray (N_ENVS, T_max, 7)  arm-joint (Actuator1-7) trajectories.
        T_max is the length of the longest per-env plan; shorter plans are
        padded by repeating their final waypoint.

    Execution pattern (vectorised, 2 sim steps per waypoint):
        _arm_cols = [_dof_idx[jn] for jn in ARM_JOINT_NAMES]
        _mg_trajs = plan_motion_all_envs(warm_cmds, cur_cmds)  # (N, T, 7)
        for _wi in range(_mg_trajs.shape[1]):
            cur_cmds[:, _arm_cols] = _mg_trajs[:, _wi, :]
            robots.set_joint_position_targets(cur_cmds)
            world.step(render=False)
            world.step(render=False)
    """
    import boilerplate_runtime as _brt
    import torch

    N        = _brt._N_ENVS
    mg       = _brt._MOTION_GEN
    ta       = _brt._MOTION_GEN_TENSOR_ARGS
    solver   = _brt._IK_OPEN
    dof_idx  = _brt._dof_idx

    start_arr = np.asarray(start_cmds_full, dtype=np.float64)
    goal_arr  = np.asarray(goal_cmds_full,  dtype=np.float64)
    arm_col   = [dof_idx[jn] for jn in _MG_ARM_JOINT_NAMES if jn in dof_idx]
    start_arm = start_arr[:, arm_col]  # (N, 7)
    goal_arm  = goal_arr[:, arm_col]   # (N, 7)

    def _lin_traj(s, g, n):
        return np.array([(1 - t/(n-1))*s + (t/(n-1))*g for t in range(n)])

    # No MotionGen — full linear fallback
    if mg is None or solver is None:
        trajs = np.stack([_lin_traj(start_arm[ei], goal_arm[ei], n_wp_fallback)
                          for ei in range(N)])  # (N, n_wp_fallback, 7)
        print(f"MOTION_GEN_FALLBACK: linear interp ({n_wp_fallback} wps, mg unavailable)", flush=True)
        return trajs

    from curobo.wrap.reacher.motion_gen import MotionGenPlanConfig as _MGPlanCfg
    from curobo.types.math import Pose as _CuPose
    from curobo.types.state import JointState as _CuJS

    # Batch FK for all envs — returns (N,3) positions and (N,4) quats in base_link frame
    goal_positions, goal_quats = solver.fk_pose_batch(goal_arm)  # (N,3), (N,4)

    all_trajs = []
    n_success = 0
    for ei in range(N):
        try:
            _pos_t  = torch.tensor(goal_positions[ei:ei+1].astype(np.float32), device=ta.device)
            _quat_t = torch.tensor(goal_quats[ei:ei+1].astype(np.float32),     device=ta.device)
            goal_pose   = _CuPose(position=_pos_t, quaternion=_quat_t)
            start_state = _CuJS.from_numpy(
                joint_names=_MG_ARM_JOINT_NAMES,
                position=start_arm[ei:ei+1].astype(np.float32),  # (1,7)
                tensor_args=ta,
            )
            result = mg.plan_single(
                start_state, goal_pose,
                _MGPlanCfg(max_attempts=5, enable_graph=True, enable_opt=True),
            )
            ok = bool(result.success[0]) if result.success is not None else False
            if ok:
                traj = result.get_interpolated_plan().position.cpu().numpy()  # (T,7)
                n_success += 1
            else:
                traj = _lin_traj(start_arm[ei], goal_arm[ei], n_wp_fallback)
        except Exception as _e:
            print(f"MOTION_GEN_ENV{ei}_ERR: {_e}", flush=True)
            traj = _lin_traj(start_arm[ei], goal_arm[ei], n_wp_fallback)
        all_trajs.append(traj)

    # Pad all trajectories to T_max
    T_max = max(len(t) for t in all_trajs)
    result_out = np.zeros((N, T_max, 7), dtype=np.float64)
    for ei, traj in enumerate(all_trajs):
        T = len(traj)
        result_out[ei, :T, :] = traj
        if T < T_max:
            result_out[ei, T:, :] = traj[-1]

    print(f"MOTION_GEN_PLAN: {n_success}/{N} envs succeeded, T_max={T_max} wps "
          f"(≈{T_max*0.02:.1f}s at 50 Hz)", flush=True)
    return result_out


# ─── Module-level state (set by init_render / init_runtime) ───────────────────

# ── World-to-base_link frame transform (USD pipeline) ─────────────────────────
# The robot USD was converted from realkinova_xhand_right.urdf which has a
# Frame transform: env-local (Isaac Sim) → cuRobo base_link frame.
# run_ik_diagnostics() reads the actual base_link pose from the USD stage and
# updates these values at runtime. Until then, defaults are identity (no-op)
# so IK targets are passed through unchanged — safe when base_link is near origin.
_WORLD_TO_BASE_T: np.ndarray = np.zeros(3, dtype=np.float64)
_WORLD_TO_BASE_ACTIVE: bool  = False  # auto-detected by run_ik_diagnostics
_R_WB: np.ndarray = np.eye(3, dtype=np.float64)


def disable_world_to_base_transform():
    """Call this when the robot is loaded from URDF (base_link at env origin).
    Disables the Isaac-Sim-world → cuRobo-base_link frame correction so that
    IK targets are passed directly to cuRobo without any frame conversion."""
    import boilerplate_runtime as _brt
    _brt._WORLD_TO_BASE_ACTIVE = False
    print("IK_FRAME: world_to_base transform DISABLED (URDF-loaded robot, frames aligned)", flush=True)


def run_ik_diagnostics(stage, robot_prim_path: str, init_joints_full_1d=None, ik_solver=None):
    """Read actual base_link world pose from stage, auto-calibrate IK frame transform,
    and run FK checks.

    Auto-calibration logic:
    - If base_link prim IS found in the stage (URDF-loaded robot): use its actual world
      position as the translation. The URDF-hardcoded transform is correct.
    - If base_link prim is NOT found (USD-loaded robot with merged fixed joints):
      the robot USD root IS base_link, so identity transform is correct. The hardcoded
      URDF offset [0.2032, -0.127, 0.1524] + 45°Y is WRONG — disable it.

    Must be called AFTER setup_ik() and after world.reset()/robots.initialize().
    Do NOT call ik_solver.solve_pose here — that corrupts the batch-size state.
    """
    import boilerplate_runtime as _brt
    import numpy as _np

    solver = ik_solver if ik_solver is not None else _brt._IK_OPEN
    if solver is None or not hasattr(solver, "arm_joint_names"):
        print("IK_DIAG: no IK solver available, skipping diagnostics", flush=True)
        return

    # ── 1. Read base_link world pose from stage and auto-calibrate transform ───
    try:
        from pxr import UsdGeom as _UsdGeom
        _base_path = robot_prim_path.rstrip("/") + "/base_link"
        _base_p = stage.GetPrimAtPath(_base_path)
        _base_prim_found = _base_p.IsValid()

        if _base_prim_found:
            # URDF-loaded robot: base_link prim exists at correct offset from root
            _xf = _UsdGeom.Xformable(_base_p).ComputeLocalToWorldTransform(0)
            _t  = _xf.ExtractTranslation()
            _T_info = _np.array([float(_t[0]), float(_t[1]), float(_t[2])], dtype=_np.float64)
            print(f"IK_DIAG: base_link found at world pos: {[round(v,4) for v in _T_info.tolist()]} — URDF transform is valid", flush=True)
        else:
            # USD-loaded robot: base_link merged into root — root IS base_link at origin.
            # The URDF offset [0.2032, -0.127, 0.1524] + 45°Y is WRONG here.
            # Disable it so IK targets pass through unchanged (world frame = base frame).
            _p = stage.GetPrimAtPath(robot_prim_path)
            _xf = _UsdGeom.Xformable(_p).ComputeLocalToWorldTransform(0)
            _t  = _xf.ExtractTranslation()
            _T_info = _np.array([float(_t[0]), float(_t[1]), float(_t[2])], dtype=_np.float64)
            print(f"IK_DIAG: base_link not found (USD with merged joints), robot root at: {[round(v,4) for v in _T_info.tolist()]}", flush=True)

            if solver._transform_active and _np.linalg.norm(solver._t_wb) > 0.01:
                # Disable the wrong URDF transform; world frame = base_link frame
                for _s in [solver] + ([_brt._IK_CLOSED] if _brt._IK_CLOSED not in (None, solver) else []):
                    if _s is not None and hasattr(_s, '_t_wb'):
                        _s._t_wb           = _np.zeros(3, dtype=_np.float64)
                        _s._R_wb           = _np.eye(3,  dtype=_np.float64)
                        _s._R_wb_T         = _np.eye(3,  dtype=_np.float64)
                        _s._transform_active = False
                print("IK_CALIB: disabled URDF transform — USD robot root = base_link, using identity", flush=True)
            else:
                print("IK_DIAG: transform already identity or inactive", flush=True)
    except Exception as _e:
        print(f"IK_DIAG: stage pose read skipped: {_e}", flush=True)

    # ── 2. FK check: print cuRobo FK world-frame position at init pose ────────
    # Uses compute_kinematics (NOT ik_solver.solve_pose) — safe, no state side-effects.
    try:
        if init_joints_full_1d is not None:
            import torch as _torch
            _arm_names = solver.arm_joint_names
            _arm_q = _np.array([float(init_joints_full_1d[_brt._dof_idx[jn]])
                                 for jn in _arm_names if jn in _brt._dof_idx],
                                dtype=_np.float32)
            if len(_arm_q) == len(_arm_names):
                _js = solver._make_joint_state(_arm_q)
                with _torch.no_grad():
                    _kin = solver._planner.compute_kinematics(_js)
                _ee_base = _kin.tool_poses.position[0, 0, 0].cpu().numpy().astype(_np.float64)
                _ee_world = solver.base_to_world(_ee_base)
                print(f"IK_DIAG: cuRobo FK base-frame:  {[round(v,4) for v in _ee_base.tolist()]}", flush=True)
                print(f"IK_DIAG: cuRobo FK world-frame: {[round(v,4) for v in _ee_world.tolist()]} (post-calibration)", flush=True)
    except Exception as _fk_e:
        print(f"IK_DIAG: FK check failed: {_fk_e}", flush=True)


_N_ENVS              = None
_env_offsets         = None
_objects             = None
_dof_idx: dict       = {}
_IK_OPEN             = None
_IK_CLOSED           = None
_MOTION_GEN          = None   # set by setup_motion_gen()
_MOTION_GEN_TENSOR_ARGS = None
_IK_BACKEND: str     = "none"
# Numpy IK kept alongside cuRobo so failed-cuRobo envs can fall back to it.
_IK_NUMPY            = None
_PHYSICS_DT: float   = 1.0 / 60.0
_frames_dir: str     = "/tmp/isaac_frames_par"
_rgb_annotator       = None
_frame_counter       = [0]
_step_counter        = [0]
_RENDER_EVERY: int   = 6
_orig_world_step     = None
_OBJECT_EXTENTS      = None
_GOAL_KEYPOINTS_BATCH = None


def init_render(world, _frames_dir_arg: str, _rgb_annotator_arg, _RENDER_EVERY_arg: int = 6):
    """Install the auto-render world.step wrapper.

    Call BEFORE the physics settle loop so settle steps are also frame-saved.
    world.step is replaced in-place with world_step_auto_render."""
    import boilerplate_runtime as _brt
    _brt._orig_world_step = world.step
    _brt._frames_dir      = _frames_dir_arg
    _brt._rgb_annotator   = _rgb_annotator_arg
    _brt._RENDER_EVERY    = _RENDER_EVERY_arg
    world.step = world_step_auto_render


def init_runtime(
    *,
    N_ENVS: int,
    env_offsets,
    objects,
    _dof_idx_arg: dict,
    _IK_OPEN_arg,
    _IK_CLOSED_arg,
    _IK_BACKEND_arg: str,
    OBJECT_EXTENTS,
    GOAL_KEYPOINTS_BATCH,
    _PHYSICS_DT_arg: float = 1.0 / 60.0,
):
    """Wire up stateful runtime helpers (IK, contact forces, keypoints).

    Call AFTER GOAL_KEYPOINTS_BATCH has been computed.
    After this call, solve_ik_batch_all_envs, get_object_contact_forces,
    keypoint_max_dist_batch etc. are all fully functional."""
    import boilerplate_runtime as _brt
    _brt._N_ENVS               = N_ENVS
    _brt._env_offsets          = env_offsets
    _brt._objects              = objects
    _brt._dof_idx              = _dof_idx_arg
    _brt._IK_OPEN              = _IK_OPEN_arg
    _brt._IK_CLOSED            = _IK_CLOSED_arg
    _brt._IK_BACKEND           = _IK_BACKEND_arg
    _brt._PHYSICS_DT           = _PHYSICS_DT_arg
    _brt._OBJECT_EXTENTS       = np.asarray(OBJECT_EXTENTS, dtype=np.float64)
    _brt._GOAL_KEYPOINTS_BATCH = np.asarray(GOAL_KEYPOINTS_BATCH, dtype=np.float64)


# ─── Stateful helpers (use module globals set by init_render / init_runtime) ───

def _save_frame():
    _frame_counter[0] += 1
    try:
        import cv2
        _rgb = _rgb_annotator.get_data()
        if _rgb is not None and hasattr(_rgb, "size") and _rgb.size > 0:
            cv2.imwrite(
                f"{_frames_dir}/frame_{_frame_counter[0]:06d}.png",
                cv2.cvtColor(_rgb, cv2.COLOR_RGB2BGR),
            )
    except Exception:
        pass


def world_step_auto_render(render=False):
    _step_counter[0] += 1
    if _step_counter[0] % _RENDER_EVERY == 0:
        _orig_world_step(render=True)
        try:
            import omni.replicator.core as _rep
            _rep.orchestrator.step(rt_subframes=1)
        except Exception:
            pass
        _save_frame()
    else:
        _orig_world_step(render=False)


def solve_ik_env0(target_pos, target_quat_wxyz, seed_joints_1d):
    """Single-env IK in env-0 frame. Returns full (n_dof,) joint vector.
    Uses whichever backend is available. Returns seed on failure."""
    if _IK_OPEN is None:
        return np.array(seed_joints_1d, dtype=np.float64)
    seed_1d = np.asarray(seed_joints_1d, dtype=np.float64).flatten()
    try:
        t_pos  = np.asarray(target_pos, dtype=np.float64).flatten()[:3]
        q_init = {jn: float(seed_1d[_dof_idx[jn]])
                  for jn in _IK_OPEN.arm_joint_names if jn in _dof_idx}
        q_sol, _ok, _err = _IK_OPEN.solve_ik_position(
            target_pos=t_pos, q_init=q_init, reg_weight=0.01)
        if not _ok:
            print(f"IK_WARN: err={_err:.4f}", flush=True)
        result_dof = seed_1d.copy()
        for jn, val in q_sol.items():
            if jn in _dof_idx:
                result_dof[_dof_idx[jn]] = float(val)
        return result_dof
    except Exception as _e:
        import traceback as _tb
        print(f"IK_EXCEPTION: {_e}\n{_tb.format_exc()}", flush=True)
        return seed_1d.copy()


def get_ik_ee_quats_all_envs(cmds_full: np.ndarray) -> np.ndarray:
    """Return (N, 4) xhand_mount_right wxyz quaternions via FK from current arm joints.

    Uses the CuRobo FK model to compute the exact orientation of the IK EE link
    (xhand_mount_right) for each env.  Call this after Phase 2a to capture the
    wrist orientation found by the cold-start IK, then pass the result as
    ``target_quats`` to ``solve_ik_batch_all_envs`` to constrain wrist orientation.
    prevent the wrist from rotating while the arm moves closer to the object.

    Falls back to identity quaternions if cuRobo FK is unavailable.
    """
    solver = _IK_OPEN
    if solver is None or not hasattr(solver, "fk_pose_batch"):
        N = len(cmds_full)
        return np.tile([1., 0., 0., 0.], (N, 1)).astype(np.float64)
    arm_col   = [_dof_idx[jn] for jn in solver.arm_joint_names if jn in _dof_idx]
    seeds_arm = np.asarray(cmds_full, dtype=np.float64)[:, arm_col]   # (N, 7)
    _, quats  = solver.fk_pose_batch(seeds_arm)  # (N, 4) wxyz
    return quats


def get_ik_ee_poses_all_envs(cmds_full: np.ndarray):
    """Return FK positions (N,3) and wxyz quaternions (N,4) of xhand_mount_right.

    IMPORTANT — pass the RIGHT joint array depending on your question:

      get_ik_ee_poses_all_envs(cmds)                        ← FK on IK-solution joints.
        Answers: "where does the IK WANT xhand_mount_right to be?"
        Error vs IK target is always ~0 (it just checks the IK algebra). This does
        NOT tell you anything about the physical robot in Isaac Sim.

      get_ik_ee_poses_all_envs(robots.get_joint_positions()) ← FK on ACTUAL robot joints.
        Answers: "where is xhand_mount_right ACTUALLY in physics right now?"
        Compare this to cmds FK to check convergence; compare to knuckle centroid
        (get_ee_pos_all_envs) to calibrate the xhand_mount_right → knuckle offset.

    Note: xhand_mount_right is approximately IK_EE_MOUNT_ADJ_M (~0.10 m) BEHIND the
    knuckle centroid along the approach direction. This offset must be added to IK
    targets so the knuckle centroid lands at the desired standoff from the object:
        ik_target = obj_pos + approach_dir * (standoff_m + IK_EE_MOUNT_ADJ_M)

    Args:
        cmds_full: (N, n_dof) full joint array — pass IK solution OR actual joints.

    Returns:
        positions : (N, 3) float64 — xhand_mount_right world-frame position per env
                    (env_offsets already added).
        quats     : (N, 4) float64 — wxyz quaternion per env.
    Falls back to zeros/identity if cuRobo FK unavailable.
    """
    solver = _IK_OPEN
    N = len(cmds_full)
    if solver is None or not hasattr(solver, "fk_pose_batch"):
        return np.zeros((N, 3), dtype=np.float64), np.tile([1., 0., 0., 0.], (N, 1)).astype(np.float64)
    arm_col   = [_dof_idx[jn] for jn in solver.arm_joint_names if jn in _dof_idx]
    seeds_arm = np.asarray(cmds_full, dtype=np.float64)[:, arm_col]   # (N, 7)
    positions, quats = solver.fk_pose_batch(seeds_arm)  # (N,3), (N,4)
    # FK positions are in env-0 frame; add env offsets to get world frame
    positions_world = positions + _env_offsets
    return positions_world, quats


def solve_ik_for_env(env_i, target_world, target_quat_wxyz, seed_joints_1d):
    """Per-env IK (subtracts env offset). Kept for compatibility; prefer solve_ik_batch_all_envs."""
    t0 = np.asarray(target_world, dtype=np.float64) - _env_offsets[env_i]
    return solve_ik_env0(t0, target_quat_wxyz, seed_joints_1d)


def solve_ik_batch_all_envs(targets_world, seeds_full, closed_hand=False,
                             target_quats=None, servo=False, servo_retract=None):
    """Solve IK for ALL N_ENVS in one call. USE THIS instead of the per-env loop.

    With cuRobo backend this is a single GPU dispatch — O(1) regardless of N_ENVS.
    With numpy fallback it runs the sequential loop internally.

    Args:
        targets_world : (N_ENVS, 3) desired EE world-frame position per env.
        seeds_full    : (N_ENVS, n_dof) current joint positions.
        closed_hand   : False for Phases 2 & 3 (approach/grasp, hand open).
                        True  for Phase 4 (transport, hand closed).
        target_quats  : (N_ENVS, 4) desired EE wrist orientations (wxyz), or None.
        servo         : Deprecated — ignored.  Always uses cold-start.
        servo_retract : Deprecated — ignored.
    Returns:
        cmds : (N_ENVS, n_dof) float64 — arm joints replaced by IK solution,
               hand joints copied unchanged from seeds_full.
               Rows where IK fails retain the seed arm joints."""
    solver = _IK_CLOSED if closed_hand else _IK_OPEN
    cmds   = np.asarray(seeds_full, dtype=np.float64).copy()
    if solver is None:
        return cmds
    tgts_env0 = np.asarray(targets_world, dtype=np.float64) - _env_offsets   # (N,3)

    # ── Frame transform: Isaac Sim env-local → cuRobo base_link frame ────────
    if _WORLD_TO_BASE_ACTIVE:
        tgts_env0 = (tgts_env0 - _WORLD_TO_BASE_T) @ _R_WB

    arm_col   = [_dof_idx[jn] for jn in solver.arm_joint_names if jn in _dof_idx]
    seeds_arm = cmds[:, arm_col]                                               # (N,7)
    # Prepare orientation targets: None (pos-only) or (N,4) wxyz array
    _tgt_quats = None
    if target_quats is not None:
        _tgt_quats_arr = np.asarray(target_quats, dtype=np.float64)
        if _tgt_quats_arr.ndim == 2 and _tgt_quats_arr.shape == (len(cmds), 4):
            _tgt_quats = _tgt_quats_arr.copy()
            for _ri in range(len(_tgt_quats)):
                if not np.any(np.isfinite(_tgt_quats[_ri])):
                    _tgt_quats[_ri] = [1.0, 0.0, 0.0, 0.0]
        elif _tgt_quats_arr.ndim == 1 and len(_tgt_quats_arr) == 4:
            _tgt_quats = np.tile(_tgt_quats_arr, (len(cmds), 1))
    if _IK_BACKEND == "curobo":
        q_batch, _succ = solver.solve_ik_batch(tgts_env0, seeds_arm,
                                                target_quats=_tgt_quats)
        n_fail = int((~_succ).sum())
        if n_fail > 0:
            _brt._ik_fail_step_count = getattr(_brt, '_ik_fail_step_count', 0) + 1
            if _brt._ik_fail_step_count <= 3 or _brt._ik_fail_step_count % 50 == 0:
                _dists = np.linalg.norm(tgts_env0, axis=1)
                print(f"IK_FAIL_COUNT: {n_fail}/{len(_succ)} "
                      f"z=[{tgts_env0[:,2].min():.3f},{tgts_env0[:,2].max():.3f}] "
                      f"dist_from_base=[{_dists.min():.3f},{_dists.max():.3f}]", flush=True)
        else:
            _brt._ik_fail_step_count = 0

        for out_i, col in enumerate(arm_col):
            cmds[:, col] = q_batch[:, out_i]
        return cmds
    # numpy fallback — sequential CPU loop (target_quats ignored for numpy backend)
    for ei in range(len(cmds)):
        q_init = {jn: float(seeds_arm[ei, k])
                  for k, jn in enumerate(solver.arm_joint_names)}
        q_sol, _ok, _err = solver.solve_ik_position(
            tgts_env0[ei], q_init=q_init, reg_weight=0.01)
        for jn, val in q_sol.items():
            if jn in _dof_idx:
                cmds[ei, _dof_idx[jn]] = float(val)
    return cmds


def get_object_contact_forces():
    """Return (N_ENVS, 3) net contact forces on each object in world frame (Newtons).
    Returns a zero array gracefully if contact tracking is unavailable."""
    try:
        raw = _objects.get_net_contact_forces(dt=_PHYSICS_DT)
        if raw is None:
            return np.zeros((_N_ENVS, 3), dtype=np.float64)
        return np.asarray(raw, dtype=np.float64)
    except Exception:
        return np.zeros((_N_ENVS, 3), dtype=np.float64)


def keypoint_max_dist_batch(positions, quats, goal_kps=None):
    """Returns (N,) array of max keypoint distance per env.
    goal_kps: (N,4,3) per-env goals  → compare each env to its own goal  [default: GOAL_KEYPOINTS_BATCH]
              (4,3)   shared goal     → broadcast to all envs              [legacy single-goal mode]
    NOTE: call with no goal_kps argument to get per-env evaluation using the aligned batch goals."""
    kps  = compute_keypoints_batch(positions, quats)   # (N,4,3)
    _gkp = _GOAL_KEYPOINTS_BATCH if goal_kps is None else np.asarray(goal_kps, dtype=np.float64)
    if _gkp.ndim == 2:   # (4,3) shared → broadcast
        dists = np.linalg.norm(kps - _gkp[None], axis=2)
    else:                # (N,4,3) per-env
        dists = np.linalg.norm(kps - _gkp, axis=2)
    return dists.max(axis=1)   # (N,)
